### ISSUE TITLE
i try to build a rpi zero classic buildroot img

### ISSUE THREAD

**Issue by perou64** [Shivelight/pOOBs4-buildroot#1]
i have an error to compile a rpi0 buildroot with my raspbian 32 bits distro
my rpi0 defconfig

# Target   
BR2_arm=y
BR2_arm1176jzf_s=y
BR2_ARM_EABIHF=y

# Linux headers same as kernel, a 5.10 series
BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_5_10=y

BR2_TOOLCHAIN_BUILDROOT_CXX=y

BR2_LINUX_KERNEL=y
BR2_LINUX_KERNEL_CUSTOM_TARBALL=y
BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION="$(call github,raspberrypi,linux,9878a118cbdb7779fd15caa45915d22bff381ba3)/linux-9878a118cbdb7779fd15caa45915d22bff381ba3.tar.gz"
BR2_LINUX_KERNEL_DEFCONFIG="bcmrpi"

# Build the DTBs for A/B from the kernel sources: the zero is the same
# as the A+ model, just in a different form-factor
BR2_LINUX_KERNEL_DTS_SUPPORT=y
BR2_LINUX_KERNEL_INTREE_DTS_NAME="bcm2708-rpi-zero"

BR2_LINUX_KERNEL_NEEDS_HOST_OPENSSL=y

BR2_PACKAGE_RPI_FIRMWARE=y
BR2_PACKAGE_RPI_FIRMWARE_BOOTCODE_BIN=y
BR2_PACKAGE_RPI_FIRMWARE_VARIANT_PI=y
BR2_PACKAGE_RPI_FIRMWARE_CONFIG_FILE="board/raspberrypi0/config_default.txt"
# BR2_PACKAGE_RPI_FIRMWARE_INSTALL_DTB_OVERLAYS is not set

# Required tools to create the SD image
BR2_PACKAGE_HOST_DOSFSTOOLS=y
BR2_PACKAGE_HOST_GENIMAGE=y
BR2_PACKAGE_HOST_MTOOLS=y

# Filesystem / image
BR2_TARGET_ROOTFS_EXT2=y
BR2_TARGET_ROOTFS_EXT2_4=y
BR2_TARGET_ROOTFS_EXT2_SIZE="120M"
# BR2_TARGET_ROOTFS_TAR is not set
BR2_ROOTFS_POST_BUILD_SCRIPT="$(BR2_EXTERNAL_pOOBs4_PATH)/board/poobs4/common/post_build.sh"
BR2_ROOTFS_POST_IMAGE_SCRIPT="board/raspberrypi0/post-image.sh"

# Bootloader
BR2_TARGET_UBOOT=y
BR2_TARGET_UBOOT_BUILD_SYSTEM_KCONFIG=y
BR2_TARGET_UBOOT_CUSTOM_VERSION=y
BR2_TARGET_UBOOT_CUSTOM_VERSION_VALUE="2021.04"
BR2_TARGET_UBOOT_BOARD_DEFCONFIG="rpi_zero"
BR2_TARGET_UBOOT_NEEDS_DTC=y
BR2_TARGET_UBOOT_NEEDS_PYTHON3=y
BR2_TARGET_UBOOT_NEEDS_PYLIBFDT=y
BR2_TARGET_UBOOT_SPL=y
BR2_TARGET_UBOOT_SPL_NAME="u-boot-sunxi-with-spl.bin"

# Toolchain
# enable wchar support for php
BR2_TOOLCHAIN_BUILDROOT_WCHAR=y

# Host Utilities
BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_5_12=y
BR2_PACKAGE_HOST_UBOOT_TOOLS=y
BR2_PACKAGE_HOST_UBOOT_TOOLS_BOOT_SCRIPT=y
BR2_PACKAGE_HOST_UBOOT_TOOLS_BOOT_SCRIPT_SOURCE="board/orangepi/orangepi-zero/boot.cmd"
BR2_PACKAGE_HOST_UBOOT_TOOLS=y
BR2_PACKAGE_HOST_DOSFSTOOLS=y
BR2_PACKAGE_HOST_GENIMAGE=y
BR2_PACKAGE_HOST_MTOOLS=y

# use haveged for better entropy
BR2_PACKAGE_URANDOM_SCRIPTS=n
BR2_PACKAGE_HAVEGED=y

# wireless support
BR2_PACKAGE_IW=y
BR2_PACKAGE_WIRELESS_TOOLS=y
BR2_PACKAGE_WIRELESS_TOOLS_LIB=y
BR2_PACKAGE_WPA_SUPPLICANT=y
BR2_PACKAGE_WPA_SUPPLICANT_NL80211=y
BR2_PACKAGE_WPA_SUPPLICANT_CLI=y

# spi flash support
BR2_PACKAGE_MTD=y

# busybox
BR2_PACKAGE_BUSYBOX_CONFIG="package/busybox/busybox-minimal.config"
BR2_PACKAGE_BUSYBOX_CONFIG_FRAGMENT_FILES="$(BR2_EXTERNAL_pOOBs4_PATH)/board/poobs4/common/busybox-minimal-extra.config"

# openssh
BR2_PACKAGE_OPENSSH=y

# hostapd
BR2_PACKAGE_HOSTAPD=y

# dnsmasq
BR2_PACKAGE_DNSMASQ=y
BR2_PACKAGE_DNSMASQ_DHCP=y

**Comment by Shivelight** [comment]
Can you share the error log?

**Comment by perou64** [comment]
It's an error of gmp because i use a 32bits distro for compilé and i need 64 bits as i understand. I will try in another most powerfull pc in Windows 10 and virtual machine.

Do you think it could work?

**Comment by Shivelight** [comment]
I'm not sure about 64 bit requirement but it should work on Windows, you can use the official vagrantfile too.

https://buildroot.org/downloads/manual/manual.html#getting-buildroot

**Comment by perou64** [comment]
i can't compile with windows 10, then windows antivirus block all in powershell.
the error in my linux pc give that :
checking size of mp_limb_t... 4
configure: error: Oops, mp_limb_t is 32 bits, but the assembler code
in this configuration expects 64 bits.
You appear to have set $CFLAGS, perhaps you also need to tell GMP the
intended ABI, see "ABI and ISA" in the manual.
make: *** [package/pkg-generic.mk:285: /home/pi/buildroot/output/build/host-gmp-6.2.1/.stamp_configured] Error 1

I never compile any os , i'll try for the first time but it's seem to be more difficult that paste command in terminal :(

**Comment by Shivelight** [comment]
I will try building it on my machine and see if I can find the solution.

**Comment by perou64** [comment]
Thanks you

**Comment by Shivelight** [comment]
@perou64 I don't have the capacity to make it work on 32 bit system. This is also my first time using buildroot or building a Linux system. I was able to easily build on 64 bit system, but since the original Pi Zero doesn't have a Wi-Fi module, I don't exactly know how to support external Wi-Fi adapter. I imagine supporting as much as possible card is the best way.

Anyway, what Wi-Fi dongle do you have? I'll try to build a specific image for your setup and see if it works.

**Comment by perou64** [comment]
i use a "Realtek RTL8188CUS 802.11n WLAN Adapter" or a "Ralink MT7601U Wireless Adapter". it works with raspbian and libreelec without any installation. i copy all wifi firmware present in libreelec rpi0 9.2.6 you can find here:
 https://www.mediafire.com/file/118fmr0w175ig5b/firmware.7z/file

**Comment by Shivelight** [comment]
I notice that if you use the USB OTG port for a Wi-Fi dongle, then you wouldn't be able to use the USB emulation without hardware modification :thinking:

**Comment by perou64** [comment]
Ok, i understand it's impossible for this reason to do the autojailbreak with a pi zero classic. I have to buy a rpi zéro wh w or 2w for it. Thanks
