### ISSUE TITLE
Banana Pi M2 Zero won't boot.

### ISSUE THREAD

**Issue by Snooba** [Shivelight/pOOBs4-buildroot#13]
I have used the image provided in release, and the Banana pi will refuse to boot at all (the red led should hearbeat blink on boot, but stays on a solid red, and no wifi comes up).
Same sdcard is able to boot raspbian without issues, so I don't think it's a faulty sdcard or an underpowered board.
Any ideas?

**Comment by Shivelight** [comment]
Probably my fault when doing some cleanup, I will try to fix it.

**Comment by Snooba** [comment]
Thanks!

**Comment by Shivelight** [comment]
Try this build https://github.com/Shivelight/pOOBs4-buildroot/actions/runs/1850528178

**Comment by Snooba** [comment]
This build works, and the wifi shows up correctly. Many thanks!
