### ISSUE TITLE
Replacing new version of GoldHen

### ISSUE THREAD

**Issue by itisnotold** [Shivelight/pOOBs4-buildroot#15]
What should we do if we want to replace a new version of GoldHen, but keep the host.
Should we change PL1 in index. html?

Thx for the nice project and open source codes:)

**Comment by Shivelight** [comment]
> Should we change PL1 in index. html?

Correct.

I wrote this node,js script a while ago, might be useful for you. I don't speak javascript nor node.js so pardon me.
```js
fs.readFile('goldhen_2.1_900.bin', function(err, data) {
    fs.writeFile("goldhen21.js", "var PL1 = [" + Array.prototype.slice.call(data) + "];", () => {});
});
```

I wanted to make it easy to change the payload in the future.

**Comment by itisnotold** [comment]
Thank you for the response and the code. I am looking forward to see the next version of your code:)

**Comment by pcfreaxx** [comment]
Can you explain it for a noob? I need GoldHen 2.2.2 and it always fails with a usb Stick manually. :-(

**Comment by Shivelight** [comment]
> Can you explain it for a noob? I need GoldHen 2.2.2 and it always fails with a usb Stick manually. :-(

Already updated on the main branch, replace `index.html` on your board with this:
https://github.com/Shivelight/pOOBs4-buildroot/blob/aaf74e295c624f5ef40e3ca1a1038622ecd0c2cf/board/poobs4/common/rootfs_overlay/var/www/html/index.html

**Comment by itisnotold** [comment]
> > Can you explain it for a noob? I need GoldHen 2.2.2 and it always fails with a usb Stick manually. :-(
> 
> Already updated on the main branch, replace `index.html` on your board with this: https://github.com/Shivelight/pOOBs4-buildroot/blob/aaf74e295c624f5ef40e3ca1a1038622ecd0c2cf/board/poobs4/common/rootfs_overlay/var/www/html/index.html

I have complied the current source code and it is 2.0b2, also I a have compared with the index.html file that you have referenced here and it is identical with source code. I think we do not have the correct PL1

**Comment by itisnotold** [comment]
> Can you explain it for a noob? I need GoldHen 2.2.2 and it always fails with a usb Stick manually. :-(

Also, clear website data / cookies in the web site browser, so the data cached again:)
browser->setting->delete cookies/clear website data
