### ISSUE TITLE
CONFIG FOR OLD RASPBERRY 1

### ISSUE THREAD

**Issue by chicco83** [Shivelight/pOOBs4-buildroot#2]
I have an old rasperry 1. it could be perfect to run pOOBs4
can you please make a config for it?

**Comment by Shivelight** [comment]
AFAIK the Raspberry Pi 1 does not have a USB OTG port, so it will host pOOBs4 without the USB emulation. But if you want an offline host without the USB emulation, I will try.

**Comment by chicco83** [comment]
You are right. Without OTG it Is unuseful.
Maybe write on github a list of not compatibile boards to avoid stupid questions like mine.

**Comment by Shivelight** [comment]
I'm okay with questions :)

**Comment by Shivelight** [comment]
Hey @chicco83, may I ask which version of the original Raspberry Pi model do you have? Is it A/A+ or B/B+?

**Comment by Shivelight** [comment]
Closing this, the original Raspberry Pi can't do OTG + WiFi dongle unless modified. Same issue with the original Raspberry Pi Zero.
