### ISSUE TITLE
Banana Pi M2 Zero Improvement

### ISSUE THREAD

**Issue by Shivelight** [Shivelight/pOOBs4-buildroot#4]
Improvement discussion for Banana Pi M2 Zero

**Comment by DanielVolz** [comment]
Ok, I found a more "official" way to deal with this WiFi timing problem. 

I added `wait-delay 15` to the `/etc/network/interface` file. 
It will wait a **maximum** of 15 seconds for wlan0 but uses it instantly when it comes up earlier. 

In my test there was no noticeable delay. 

I think we could add `wait-delay 15` to `0001-Setup-wlan-interface.sh` to solve the timing problem in a more general way.

```
#!/bin/sh

if ! grep -Fq "iface wlan0 inet static" output/target/etc/network/interfaces ; then
	echo "
# for wlan0
auto wlan0
iface wlan0 inet static 
  hostname \$(hostname)
  address 10.0.0.1
  netmask 255.0.0.0
  network 10.0.0.0
  broadcast 10.255.255.255
  wait-delay 15" >> output/target/etc/network/interfaces
fi

exit 0

```

**Comment by Shivelight** [comment]
Good find! We will go with this solution :+1: 

---

For someone surfing by, this is work because buildroot's `ifupdown-scripts` package ships with `wait_iface` hook script in `if-pre-up.d` 
https://github.com/buildroot/buildroot/blob/master/package/ifupdown-scripts/network/if-pre-up.d/wait_iface

If you look at the script, it checks for `IF_WAIT_DELAY`, which is set by `ifupdown` here:
https://github.com/mirror/busybox/blob/205042c07a3bf6c8e685c434713f2a9e46630cd0/networking/ifupdown.c#L1141

Explanation from [interfaces(5)](https://manpages.debian.org/bullseye/ifupdown/interfaces.5.en.html#ENVIRONMENT_VARIABLES):

> Additionally, all options given in an interface definition stanza are exported to the environment in upper case with "IF_" prepended and with hyphens converted to underscores and non-alphanumeric characters discarded.

Thus `wait-delay` -> `IF_WAIT_DELAY`.

:clap: :clap:

**Comment by Shivelight** [comment]
@DanielVolz do you want to open a PR, or should I?

**Comment by DanielVolz** [comment]
> @DanielVolz do you want to open a PR, or should I?

I can do it.
Thanks for the explanation above. Very interesting!

**Comment by Shivelight** [comment]
*This is continuation of #5 discussion.*
